# https://taskfile.dev
version: '3'
vars:
  BINFILE: awslogcheck
  IMG: sgaunet/awslogcheck:latest

tasks:
  default:
    desc: "List tasks"
    cmds:
      - task -a

  bin:
    desc: "Build binary"
    cmds:
      - go mod tidy
      - CGO_ENABLED=0 go build .
      - upx ./{{.BINFILE}}

  image:
    desc: "Build docker image"
    deps: 
    - default
    sources:
      - ./{{.BINFILE}}
      - Dockerfile
      - resources
    cmds:
      - docker build . -t {{.IMG}}
      - docker push {{.IMG}}

  snapshot:
    desc: "Create a snapshot release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean