# https://taskfile.dev
version: '3'
vars:
  BINFILE: awslogcheck
  IMG: ghcr.io/sgaunet/awslogcheck:latest

tasks:
  default:
    desc: "List tasks"
    cmds:
      - task -a

  build:
    desc: "Build binary"
    cmds:
      - go mod tidy
      - CGO_ENABLED=0 go build .
      - upx ./{{.BINFILE}}

  image:
    desc: "Build docker image"
    deps: 
    - snapshot
    cmds:
      - docker push ghcr.io/sgaunet/awslogcheck:latest-amd64
      - docker push ghcr.io/sgaunet/awslogcheck:latest-arm64v8
      - docker push ghcr.io/sgaunet/awslogcheck:latest-armv6
      - docker push ghcr.io/sgaunet/awslogcheck:latest-armv7
      - docker manifest create --amend ghcr.io/sgaunet/awslogcheck:latest ghcr.io/sgaunet/awslogcheck:latest-amd64 ghcr.io/sgaunet/awslogcheck:latest-arm64v8 ghcr.io/sgaunet/awslogcheck:latest-armv6 ghcr.io/sgaunet/awslogcheck:latest-armv7
      - docker manifest push ghcr.io/sgaunet/awslogcheck:latest

  snapshot:
    desc: "Create a snapshot release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --skip validate